export const listaPiadas = [
    'Por que enviar SPAM é algo justificável?\nPorque os fins justificam os emails',
    'Que tipo de computador está bombando nas redes sociais?\nO deskTOP',
    'Qual o endereço do site do cavalo?\nwww.cavalo pontocom pontocom pontocom',
    'Por que o mouse é muito mimado?\nPorque tudo o que ele quer, o mouse pad',
    'Qual doença se pode pegar ao usar notebook?\nA LAPTOPspirose',
    'O que uma impressora falou para a outra?\nEssa folha aí no chão é sua, ou é impressão minha?',
    'O que o Schwarzenegger disse quando instalaram o Windows XP pra ele?\nInstala o Vista, baby',
    'O que é um terapeuta?\n1.024 gigapeutas',
    'Para qual santo você reza quando esquece a senha?\nSão Login',
    'O dono do site esqueceu a própria senha, qual o nome do filme?\nEsqueceram Admin',
    'Quando você percebe que seu computador está velho?\nQuando a placa-mãe já virou avó',
    'Por que antigamente a Internet não subia de elevador?\nPorque era Internet de-escada',
    'Qual a diferença entre Hardware e Software?\nO Hardware você chuta, o Software você xinga',
    'Na frase "Fulano foi mal em todas as provas", onde está o sujeito?\nNa Internet',
    'Qual é a gata que entra e já sai do chat?\nA Hello, Quit',
    'Por que os sites de emprego não informam nada?\nPorque lá as informações são vagas',
    'Quantos programadores são necessários para trocar uma lâmpada?\nNenhum, isso é problema de Hardware',
    'Qual linguagem de programação o Han Solo detesta?\nJabbaScript',
    'int x=10; int y=10; return x+y; // Qual o nome do filme?\nO Código dá Vinte',
    'Qual a música preferida do Sérgio Reis?\nToda vez que eu via Java pela estrada de Ouro Fino',
    'Que música Raul Seixas cantava quando pediam para ele programar em Java?\nEu prefiro C ...',
]